# Generated by Django 6.0.4 on 2026-04-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_lignetelephonique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('agent', 'Agent'), ('agent_technique', 'Agent Technique'), ('agent_annexe', 'Agent Annexe'), ('admin', 'Admin'), ('admin_it', 'Admin IT')], default='client', max_length=20),
        ),
    ]
