# Generated by Django 6.0.4 on 2026-05-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_demandeit'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='email_n8n',
            field=models.EmailField(blank=True, help_text='Email source n8n (pour identifier le client par email)', max_length=254, null=True),
        ),
    ]
