# Generated by Django 6.0.4 on 2026-05-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_utilisateur_email_n8n'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeit',
            name='fichier_reponse',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeit',
            name='fichier_reponse_nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='demandeit',
            name='fichier_reponse_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('agent', 'Agent'), ('agent_technique', 'Agent Technique'), ('agent_annexe', 'Agent ACTEL'), ('admin', 'Admin'), ('admin_it', 'Admin IT')], default='client', max_length=20),
        ),
    ]
