# Generated by Django 6.0.4 on 2026-05-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centredistribution',
            name='communes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
