# Generated by Django 6.0.4 on 2026-04-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_populate_types_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='email_actif',
            field=models.BooleanField(default=True, help_text='Relais email actif pour ce ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='email_source',
            field=models.EmailField(blank=True, help_text="Email d'origine de la réclamation", max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='source',
            field=models.CharField(choices=[('web', 'Web'), ('email', 'Email')], default='web', max_length=10),
        ),
    ]
