# Generated by Django 6.0.4 on 2026-05-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_emailpending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='statut',
            field=models.CharField(choices=[('soumis', 'Soumis'), ('en_cours', 'En cours'), ('escalade_technique', 'Escaladé - Technique'), ('escalade_annexe', 'Escaladé - Annexe'), ('resolu', 'Résolu'), ('ferme', 'Fermé'), ('rejete', 'Rejeté')], default='soumis', max_length=25),
        ),
    ]
