# Generated by Django 6.0.4 on 2026-05-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_remove_ouvert_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='statut',
            field=models.CharField(choices=[('soumis', 'Soumis'), ('en_cours', 'En cours'), ('escalade', 'Escaladé'), ('resolu', 'Résolu'), ('ferme', 'Fermé'), ('rejete', 'Rejeté')], default='soumis', max_length=25),
        ),
    ]
