# Generated by Django 6.0.4 on 2026-05-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_merge_escalade_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalade',
            name='type_escalade',
            field=models.CharField(choices=[('technique', 'Technique'), ('annexe', 'ACTEL')], max_length=10),
        ),
    ]
