# Generated by Django 6.0.4 on 2026-05-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_escalade_type_escalade'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resume_ia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
