# Generated by Django 6.0.4 on 2026-04-22 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
        ('tickets', '0004_populate_types_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='expediteur_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='piece_jointe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_chat', to='tickets.piecejointe'),
        ),
    ]
