# Generated by Django 6.0.4 on 2026-04-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='via_email',
            field=models.BooleanField(default=False),
        ),
    ]
