# Generated by Django 6.0.4 on 2026-04-22 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_email_integration'),
        ('chat', '0003_message_expediteur_role_message_piece_jointe'),
    ]

    operations = [
    ]
