# Generated by Django 6.0.4 on 2026-05-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_merge_20260422_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='interne',
            field=models.BooleanField(default=False, help_text='Message interne non visible par le client'),
        ),
    ]
